### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by mstaroste** [lukasroegner/homebridge-sonos-multiroom#10]
Is it possible to set a specific album or volume with homekit automation?

**Comment by lukasroegner** [comment]
Yes, just use the SSH or HTTP actions in the new Shortcuts-like HomeKit automations in combination with the API this plugin provides.

**Comment by mstaroste** [comment]
OK great. Possible to set a sleep timer via API as well?

**Comment by lukasroegner** [comment]
For more advanced automations I would recommend the Sonos HTTP API (https://github.com/jishi/node-sonos-http-api), which you can install side-by-side on your Homebridge host. It exposes nearly all Sonos features via an HTTP API. You can use HomeKit-Shortcut-Automations and Siri-Shortcuts to consume the API.
