### ISSUE TITLE
Removing accessory with name

### ISSUE THREAD

**Issue by dprimmer14** [lukasroegner/homebridge-sonos-multiroom#11]
Hi 

I have an issue where some of the Sonos Zones are not found ona Homebridge restart (I have 18 Devices) and they devices not discovered are therefore removed from HomeKit, only to be found again after restating. 

I have moved the Discovery time out to 20,000 this helped but has not completely fixed the issue.  

It is painful to then have to add devices to the correct rooms and automations.

Is there anyway of them not being removed and if they cannot be discover showing in HomeKit with "No Response"

Otherwise awesome Plugin and more then happy to donate.

Cheers

**Comment by lukasroegner** [comment]
Hi @dprimmer14,

Without a full discovery during the startup of the plugin, the plugin is not usable. Even if I disable removing accessories that are not found, those accessories in HomeKit would be unusable until the next startup of the plugin. 

I would recommend to try increasing the timeout until all of your devices can be found using startup.
