### ISSUE TITLE
What Ports

### ISSUE THREAD

**Issue by PhillWalker** [lukasroegner/homebridge-sonos-multiroom#14]
Hello what ports does this plugin use for device discovery?

With the synology firewall on, auto discovery finds 0 devices, and can not control the previously found devices.

If you turn the firewall off, it finds devices and allows control

Homebridge port is already open in the firewall, TCP 51963, for 192.168.0.1-192.168.0.253

**Comment by lukasroegner** [comment]
Please take a look at the ports that Sonos uses for communication and streaming:
https://support.sonos.com/s/article/688?language=en_US

I think the most import ones are:
TCP: 1400, 3400, 3401, and 3500
UDP: 1900 and 1901
