### ISSUE TITLE
bug: playback stops if the original playback zone leaves the group

### ISSUE THREAD

**Issue by rfiorentino1** [lukasroegner/homebridge-sonos-multiroom#15]
Hi, Thank you for developing this plugin, it. is probably the best thing I've seen in Homebridge to properly manage Sonos groups, regardless of using in conjunction with motion sensors, etc. However, I've noticed an interesting bug; maybe I'm just missing something, but it seems as if stopping the original source of playback causes everything to stop. For example:

I start music in the living room. I then add the kitchen, so that both the living room and kitchen are playing together, grouped. If I remove the kitchen again, the living room keeps playing, and if I re-add it, the kitchen rejoins and all is well. However, if I remove the living room, the kitchen does not keep playing on it's own, presumably because the living room, which was the starting source, is no longer in the group, so multi-room gets confused? But as long as the kitchen is still playing, why can't it just continue to play alone, until another zone joins the group? Any other zone will play fine in a solo group, as long as it wasn't the initial starting zone for the playback. Not sure if this makes sense, but please let me know if I can clarify anything, or if you want me to send debug logs, etc. Do you know why this may be happening/a potential way to fix it?
 Thanks again.

**Comment by rfiorentino1** [comment]
Update: This appears to be a Spotify-only issue, and happens within the actual Sonos app when grouping/ungrouping players as well. I'll reach out to Sonos about this as well, but can anyone else confirm? Thanks so much.

**Comment by lukasroegner** [comment]
I tested the setup that you described. I'm usually using Apple Music, but also tried it out with Spotify (more specific, I'm playing a playlist). 

I could not reproduce the issue:
- Played the playlist in zone A (via Sonos app)
- Stopped playback in all zones
- Switched zone A to on (via HomeKit)
- The playlist starts
- Switched on zone B (via HomeKit)
- The playlist plays in both zones
- Switched off zone A (the original "coordinator" as it is called) (via HomeKit)
- The playlist still plays in zone B

**Comment by rfiorentino1** [comment]
Hi, thanks so much for testing this. My apologies, I forgot to mention that the music needs to be started from either Alexa or the Spotify app itself, something other than the Sonos app for this bug to happen. Once playback is started, The bug can be reproduced when grouping and ungrouping zones in the Sonos app itself or in HomeKit. But playback of Spotify from the Sonos app is the only thing that stops the spunk from occurring

**Comment by lukasroegner** [comment]
I assume that using the Spotify app does not start local playback (i.e. the phone instead of the Sonos system coordinates music streaming). One last thing you can try:
- Start playback in a zone via the Spotify app
- Open the Sonos app and add another zone to the group
- In the Sonos app, remove the original zone from the group

If that also fails, we can be sure that it is not an issue of the plugin, rather a restriction of the Sonos system.

**Comment by rfiorentino1** [comment]
Yes, that also does the same thing, stopping all playback if you ungroup with the Sonos app. But I didn't realize this until I did more testing which is why I originally opened this issue :-) I'll report back if Sonos has anything to say
