### ISSUE TITLE
API playlist issue

### ISSUE THREAD

**Issue by Ghitafjorback** [lukasroegner/homebridge-sonos-multiroom#6]
Hi Lukas
I keep running in to your awesome homebridge plugins with API supplement!

I can use all the POST api settings, except the "current-track-uri" when the uri is for a playlist. If I add the uri of a playlist, just nothing happens, there is no error of any kind. If I change the uri to a single song, everything is fine.

Can you tell me if I am doing anything wrong?
My single track uri's start with "x-sonos-spotify:spotify%3atrack...." where the playlists starts with "x-rincon-cpcontainer:1006206cspotify%3aplaylist...."

Thank you in advance
Ghita

**Comment by Ghitafjorback** [comment]
Oh, and one more thing. Once the playlist is started, would it be possible to "shuffle" through the playlist rather than "play" it?

**Comment by lukasroegner** [comment]
Hi @Ghitafjorback, I don't use Spotify, so I can't check right now. Have you tried to change the URI of the playlist, e.g.

```
x-sonos-spotify:spotify%3aplaylist....
```

**Comment by Ghitafjorback** [comment]
Hi @lukasroegner 
Yes, i tried that. it does not help unfortunately. :(

**Comment by Ghitafjorback** [comment]
I am starting to think it is simply not possible to start a playlist from Spotify via this API. I have checked a lot of other forums, and I can tell that they have the same issue.

**Comment by lukasroegner** [comment]
The plugin uses `node-sonos` as basis for communication with the Sonos system. I worked through the examples and got my hands on a Spotify account to test with...I also didn't succeed, even with custom code I added for the testing. Sometimes it worked (with the custom code) under certain circumstances, most of the time I get an error from the Sonos system when trying to start a playlist.
